export const siteMetadata = {
  title: "Xóm nhậu - Tổng hợp sự kiện trong bàn nhậu",
  headerTitle: 'XomNhau',
  description: "Xóm nhậu - Tổng hợp sự kiện trong bàn nhậu",
  language: 'vi-vn',
  theme: 'system',
  siteUrl: 'https://xomnhau.com',
  github: 'https://github.com',
  x: 'https://twitter.com/x',
  facebook: 'https://facebook.com',
  youtube: 'https://youtube.com',
  linkedin: 'https://www.linkedin.com',
  threads: 'https://www.threads.net',
  instagram: 'https://www.instagram.com',
}